# Generated by Django 4.2.2 on 2023-07-06 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 5, 36, 4, 900727, tzinfo=datetime.timezone.utc)),
        ),
    ]
