# Generated by Django 4.2.2 on 2023-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='working_days',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
