# Generated by Django 4.2.2 on 2023-07-06 06:01

import app.manager
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_email_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', app.manager.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 6, 1, 57, 355224, tzinfo=datetime.timezone.utc)),
        ),
    ]
