# Generated by Django 4.2.2 on 2023-07-05 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('date_sent', models.DateTimeField(default=datetime.datetime(2023, 7, 5, 13, 32, 6, 527539, tzinfo=datetime.timezone.utc))),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
    ]
